### ISSUE TITLE
Implement TinyMCE for Grade Feedback

### ISSUE THREAD

**Issue by PatrickFrankAIU** [PatrickFrankAIU/GradeManagerProject#5]
- [x] Investigate TinyMCE for possible adoption in the project 
- [x] Test implementation 
- [x] Implement in project

[![image](https://github.com/PatrickFrankAIU/GradeManagerProject/assets/134087916/179c6be0-817b-4752-9c12-f92bf9b5c6bb)](https://www.tiny.cloud/)

TinyMCE is a freeware JavaScript module that can be added to any project. Like SASS, it uses an HTML script tag that connects to a library through a Content Delivery Network (CDN) with this call: (Your API key goes where it says "no-api-key".)

`<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>`

**You create a text area like this:** (This is just a normal textarea. TinyMCE changes the normal functionality of any textarea in your HTML.) 
```
<body>
    <textarea id="mytextarea">Hello, World!</textarea>
</body>
```

**This is the JS call to initialize the module:** 

```
tinymce.init({
    selector: '#mytextarea'
});

```

**Customization is handled through this code:** 

```
    tinymce.init({
        selector: '#mytextarea',
        plugins: 'advlist autolink lists link image charmap print preview hr anchor pagebreak',
        toolbar_mode: 'floating',
        toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | outdent indent | link image'
    });

```

**Questions to investigate:** 
- Is registration required? 
- Does it store data in an array, variable, object, or what? 
- Can that data be added to existing data structures? 

**More info can be found here:** 
https://www.tiny.cloud/

**Comment by pmjohnston21** [comment]
@Aidan-Murphy-22 @srreed3 I wanted to make sure y'all are seeing the console errors in the dev tools; not sure if it helps you diagnose or fix the issues you're having. I hadn't looked at them at all until now and though y'all might not have, either. Going to try to add a screenshot here:
<img width="551" alt="image" src="https://github.com/PatrickFrankAIU/GradeManagerProject/assets/167406708/fc371b92-ac07-4b7e-8870-3bab409a6ce0">

After you add a grade, you get an additional error, Rose:
<img width="551" alt="image" src="https://github.com/PatrickFrankAIU/GradeManagerProject/assets/167406708/ce17b7ec-5a90-499b-892f-2b7a760f88f1">

**Comment by PatrickFrankAIU** [comment]
> @Aidan-Murphy-22 @srreed3 I wanted to make sure y'all are seeing the console errors in the dev tools; not sure if it helps you diagnose or fix the issues you're having. I hadn't looked at them at all until now and though y'all might not have, either. Going to try to add a screenshot here: <img alt="image" width="551" src="https://private-user-images.githubusercontent.com/167406708/332606357-fc371b92-ac07-4b7e-8870-3bab409a6ce0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTYwODgsIm5iZiI6MTcxNjM5NTc4OCwicGF0aCI6Ii8xNjc0MDY3MDgvMzMyNjA2MzU3LWZjMzcxYjkyLWFjMDctNGI3ZS04ODcwLTNiYWI0MDlhNmNlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxNjM2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDFlMzE4NDhhZWJhN2I3YjZlZjgzMWIwOTZhMzZkNzA5NmZiYmNhMTA3NzNhNDQxNGY1ZGIzM2I1ZjIwMDE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UqkvunynVKd7HA0MnMV88MhLOTi-N21766XaLYl1694">
> 
> After you add a grade, you get an additional error, Rose: <img alt="image" width="551" src="https://private-user-images.githubusercontent.com/167406708/332606545-ce17b7ec-5a90-499b-892f-2b7a760f88f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTYwODgsIm5iZiI6MTcxNjM5NTc4OCwicGF0aCI6Ii8xNjc0MDY3MDgvMzMyNjA2NTQ1LWNlMTdiN2VjLTVhOTAtNDk5Yi04OTJmLTJiN2E3NjBmODhmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxNjM2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTAxNWE0ZDUwNGRjNDY1N2NjMDU2MDg2MzBkNzFkMjQzOWQ2NTBjMzhkMjg4NjUzOTBiN2MzZjhkZjg5NTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IIHnsN9155JOCgKqwQYh-jFlxTgoQF5TD0LtMLyGExM">

Good observation, Penny! Some of the errors I'm seeing at my end are caused by personal browser settings (restrictions) and plugins like ad-blocking software. But others suggest that we may have some minor issues still to resolve. We'll take a closer look at it tonight in class. :-)

-- Pat

**Comment by PatrickFrankAIU** [comment]
Here's a head start from a couple things I looked up via ChatGPT: "Print from URL" lets you add content from a URL into your message in the TinyMCE window. "HR from URL" refers to adding a horizontal rule (HTML's "hr" tag), meaning you can grab an HR tag from another website that's being dynamically created by some process on that site. 

These might be used when you're supporting a scripted process that brings preformatted data from another site into a TinyMCE window. It sounds like these features may not be working at the moment, but I noticed the code they use requires Fetch, which you may be familiar with from the 300 class. 

For our purposes on this project they're probably not something we'd implement, so I wouldn't worry about it. But if we can find a simple fix then that'll be useful experience to have, so it might be worth a short investigation. You're both entering a time when you're going to have to start "picking your battles" on the learning front, just because there is so much info out there that you can leverage in your work now. But remember: Working developers don't know everything either. The true skill of a coder is in their ability to learn and adapt on the fly. So in a sense this is "bait" -- it might be worth the time... or it might not be! So think about setting a time limit on your investigation. 

We'll talk about it tonight in class. :-)
